# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5904cf9b73a4faab36946d484c5b5feb"
name = "Etch"
application_url = "https://etch.direct"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,write_cart_transforms,write_validations"

[auth]
redirect_urls = [
  "https://etch.direct/auth/callback",
  "https://etch.direct/auth/shopify/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback"
]
