api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "etch-cart-validation"
type = "function"
uid = "8531ba2e-91d6-281d-a005-45e3d2b7dc88154cbfd3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
